### ISSUE TITLE
Validating Access Tokens

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-authorization-implementation-guide#48]
https://specs.amwa.tv/info-002/branches/main/docs/4.6._Validating_Access_Tokens.html says:

"Verify the Signature, by generating a new Base64url-encoded Signature using the issuer's public key and verify that it matches the original Signature, to ensure the token has not been tampered with."

My understanding is that isn't the way it works. A Signature can only be generated by the issuer using its _private_ key (otherwise anyone could have signed any message pretending to be the issuer).

Less precise, but I think more correct:

"Verify the Signature, using the issuer's public key, to ensure the token has not been tampered with."

According to [RFC 7515 Appendix A.2.2](https://datatracker.ietf.org/doc/html/rfc7515#appendix-A.2.2), for example, this process involves an appropriate _signature verifier_ being passed the _public key_, the _signature_ and the _signing input_ (the other two parts of the JWT).

**Comment by jonathan-r-thorpe** [comment]
#49 resolves this issue
