### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by firthmj** [AMWA-TV/nmos-authorization-implementation-guide#51]
Many of the links into the specifications from INFO-002 seem to be broken.

In particular on the "Authorization Server Setup" and "Node to Authorization Server Interactions" pages, most seem to not work.

The first broken link on "Authorization Server Setup" is:
https://specs.amwa.tv/is-10/branches/v1.0.x/docs/4.4._Behaviour_-_Access_Tokens.html#registered-claims
which I think should be:
https://specs.amwa.tv/is-10/releases/v1.0.0/docs/4.4._Behaviour_-_Access_Tokens.html#registered-claims

I'm guessing a lot of the issues will be due to similar things.

Do you want me to work on creating a PR for these, or can you fix them directly?

**Comment by garethsb** [comment]
Closed by #52.
