### ISSUE TITLE
Incorrect reference in Validating Access Tokens

### ISSUE THREAD

**Issue by firthmj** [AMWA-TV/nmos-authorization-implementation-guide#55]
Hi,

I think the reference to RFC8414 Section 3 in the Validating Access Tokens document is incorrect. The document says the link is about "fetch the missing public key via the token iss claim", but section 3 of RFC8414 is about retrieving the authorization server metadata, not about retrieving public keys.

**Comment by lo-simon** [comment]
Maybe we should make it clear, using the token's `iss` claim to fetch the authorization server metadata then get the pubic key from the metadata's `jwks_uri`.

**Comment by peterbrightwell** [comment]
Part of wider review of BCP-003 suite.
Architecture Review Group review: place on backlog
