### ISSUE TITLE
keycloak set-up in need of revisiting

### ISSUE THREAD

**Issue by lo-simon** [AMWA-TV/nmos-authorization-implementation-guide#57]
Inside the [Keycloak setup](https://github.com/AMWA-TV/info-002/blob/main/docs/Authorization%20Server%20Setup.md#keycloak-setup) session, there are a number of reference links which are no longer available, due to the changes of the Keycloak website documentation. 

At the time when the `INFO-002` was written, we were using Keycloak `15.0.2`. Since then Keycloak has moved on to `21.0.0`. Our instructions may well be out of date. The whole set-up instructions are required to be revisited.

**Comment by peterbrightwell** [comment]
Part of wider review of BCP-003 suite.
Architecture Review Group review: place on backlog

**Comment by TheSaneWonko** [comment]
ARG will look into the links and create a PR.
